language: node_js

node_js:
  - "8"

install:
  - npm install

script:
  - npm run docs
  - npm run minify
  - cp arrange-client.js docs/

before_deploy:
  - git config --local user.name "hilderonny"
  - git config --local user.email "ronny.hildebrandt@avorium.de"
  - git tag "$(date +'%Y%m%d')-$(git log --format=%h -1)"

after_success:
  - npm run coveralls

jobs:
  include:
    - stage: "Documentation"
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: docs
        on:
          branch: master
    - stage: "Release"
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file: "docs/arrange-client.min.js"
        skip_cleanup: true
        overwrite: true
