language: node_js

node_js:
  - "7"

install:
  - npm install

script:
  - npm run minify
  - npm run docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs
  on:
    branch: master